server:
  port: 8443
  ssl:
    key-store: classpath:tomcat.jks
    key-store-password: tacmot
    key-password: tacmot
# Set the root logging level to WARN , but log Spring Security logs at DEBUG level
logging:
  file: readinglist.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
